import Queue from '../src/ts/queue/queue'

describe('Queue', () => {
    let queue: Queue<number>
    beforeEach(() => {
        queue = new Queue<number>()
    })
    it('starts empty', () => {
        expect(queue.size()).toStrictEqual(0)
        expect(queue.isEmpty()).toStrictEqual(true)
    })
    it('enqueues elements', () => {
        queue.enqueue(1)
        expect(queue.size()).toStrictEqual(1)
        queue.enqueue(2)
        expect(queue.size()).toStrictEqual(2)
        queue.enqueue(3)
        expect(queue.size()).toStrictEqual(3)
        expect(queue.isEmpty()).toStrictEqual(false)
    })
    it('dequeue elements', () => {
        queue.enqueue(1)
        queue.enqueue(2)
        queue.enqueue(3)
        expect(queue.dequeue()).toStrictEqual(1)
        expect(queue.dequeue()).toStrictEqual(2)
        expect(queue.dequeue()).toStrictEqual(3)
        expect(queue.dequeue()).toStrictEqual(undefined)
    })
    it('implements FIFO logic', () => {
        queue.enqueue(1)
        expect(queue.peek()).toStrictEqual(1)
        queue.enqueue(2)
        expect(queue.peek()).toStrictEqual(1)
        queue.enqueue(3)
        expect(queue.peek()).toStrictEqual(1)
        expect(queue.dequeue()).toStrictEqual(1)
        expect(queue.dequeue()).toStrictEqual(2)
        expect(queue.dequeue()).toStrictEqual(3)
        expect(queue.dequeue()).toStrictEqual(undefined)
    })
    it('allows to peek at the front element in the queue without dequeuing it', () => {
        expect(queue.peek()).toStrictEqual(undefined)
        queue.enqueue(1)
        expect(queue.peek()).toStrictEqual(1)
        queue.enqueue(2)
        expect(queue.peek()).toStrictEqual(1)
        queue.dequeue()
        expect(queue.peek()).toStrictEqual(2)
    })
    it('returns the correct size', () => {
        expect(queue.size()).toStrictEqual(0)
        queue.enqueue(1)
        expect(queue.size()).toStrictEqual(1)
        queue.enqueue(2)
        expect(queue.size()).toStrictEqual(2)
        queue.enqueue(3)
        expect(queue.size()).toStrictEqual(3)
        queue.clear()
        expect(queue.isEmpty()).toStrictEqual(true)
        queue.enqueue(1)
        queue.enqueue(2)
        queue.enqueue(3)
        expect(queue.size()).toStrictEqual(3)
        queue.dequeue()
        expect(queue.size()).toStrictEqual(2)
        queue.dequeue()
        expect(queue.size()).toStrictEqual(1)
        queue.dequeue()
        expect(queue.size()).toStrictEqual(0)
        queue.dequeue()
        expect(queue.size()).toStrictEqual(0)
    })
    it('returns if it is empty', () => {
        expect(queue.isEmpty()).toStrictEqual(true)
        queue.enqueue(1)
        expect(queue.isEmpty()).toStrictEqual(false)
        queue.enqueue(2)
        expect(queue.isEmpty()).toStrictEqual(false)
        queue.enqueue(3)
        expect(queue.isEmpty()).toStrictEqual(false)
        queue.clear()
        expect(queue.isEmpty()).toStrictEqual(true)
        queue.enqueue(1)
        queue.enqueue(2)
        queue.enqueue(3)
        expect(queue.isEmpty()).toStrictEqual(false)
        queue.dequeue()
        expect(queue.isEmpty()).toStrictEqual(false)
        queue.dequeue()
        expect(queue.isEmpty()).toStrictEqual(false)
        queue.dequeue()
        expect(queue.isEmpty()).toStrictEqual(true)
        queue.dequeue()
        expect(queue.isEmpty()).toStrictEqual(true)
    })
    it('clears the queue', () => {
        queue.clear()
        expect(queue.isEmpty()).toStrictEqual(true)
        queue.enqueue(1)
        queue.enqueue(2)
        expect(queue.isEmpty()).toStrictEqual(false)
        queue.clear()
        expect(queue.isEmpty()).toStrictEqual(true)
    })
})